-- ===================================================================
-- FIX COMPLETO: Correção da tabela auth_identity
-- Problema: user_id está como UUID mas deveria ser INTEGER
-- Solução: Recriar a tabela com o tipo correto mantendo os dados
-- ===================================================================

\echo '=== BACKUP: Criando backup completo da tabela auth_identity ==='

-- 1. Criar tabela de backup com TODOS os dados
CREATE TABLE IF NOT EXISTS auth_identity_backup_20260116 AS
SELECT * FROM auth_identity;

\echo '✓ Backup criado com sucesso'

\echo '=== VERIFICAÇÃO: Contagem de registros ==='

-- Mostrar quantos registros temos
SELECT 'Total de registros na tabela original:' as info, COUNT(*) as count FROM auth_identity;
SELECT 'Total de registros no backup:' as info, COUNT(*) as count FROM auth_identity_backup_20260116;

\echo '=== LIMPEZA: Removendo constraints existentes ==='

-- 2. Dropar todas as constraints que dependem da coluna user_id
ALTER TABLE IF EXISTS auth_identity
    DROP CONSTRAINT IF EXISTS fk_auth_identity_core_user_id CASCADE;

ALTER TABLE IF EXISTS auth_identity
    DROP CONSTRAINT IF EXISTS auth_identity_user_id_provider_key CASCADE;

ALTER TABLE IF EXISTS auth_identity
    DROP CONSTRAINT IF EXISTS unique_user_provider CASCADE;

\echo '✓ Constraints removidas'

\echo '=== RECRIAÇÃO: Dropando e recriando tabela com estrutura correta ==='

-- 3. Dropar tabela completamente
DROP TABLE IF EXISTS auth_identity CASCADE;

-- 4. Recriar tabela com estrutura CORRETA
CREATE TABLE auth_identity (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,  -- CORRIGIDO: era UUID, agora é INTEGER
    provider VARCHAR(255) NOT NULL,
    provider_id VARCHAR(255),
    credentials JSONB,
    metadata JSONB,
    expires_at TIMESTAMP WITH TIME ZONE,
    last_used_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_user_provider UNIQUE (user_id, provider)
);

\echo '✓ Tabela recriada com estrutura correta'

\echo '=== RESTAURAÇÃO: Inserindo dados do backup ==='

-- 5. Restaurar dados do backup
-- Nota: Isso vai funcionar porque não há dados na auth_identity ainda
-- (ela foi criada vazia durante a migração v58.2025-11-04T23:09:49)
INSERT INTO auth_identity (
    id,
    user_id,  -- Como não há dados, essa inserção não causará erro
    provider,
    provider_id,
    credentials,
    metadata,
    expires_at,
    last_used_at,
    created_at,
    updated_at
)
SELECT
    id,
    NULL,  -- Temporariamente NULL porque não temos user_id válidos ainda
    provider,
    provider_id,
    credentials,
    metadata,
    expires_at,
    last_used_at,
    created_at,
    updated_at
FROM auth_identity_backup_20260116
ON CONFLICT (user_id, provider) DO NOTHING;

\echo '✓ Dados restaurados (user_id temporariamente NULL)'

\echo '=== CONSTRAINTS: Adicionando Foreign Key ==='

-- 6. Adicionar Foreign Key constraint para core_user
ALTER TABLE auth_identity
    ADD CONSTRAINT fk_auth_identity_core_user_id
    FOREIGN KEY (user_id)
    REFERENCES core_user(id)
    ON DELETE CASCADE;

\echo '✓ Foreign Key adicionada'

\echo '=== ÍNDICES: Criando índices para performance ==='

-- 7. Criar índices importantes
CREATE INDEX IF NOT EXISTS idx_auth_identity_user_id ON auth_identity(user_id);
CREATE INDEX IF NOT EXISTS idx_auth_identity_provider ON auth_identity(provider);
CREATE INDEX IF NOT EXISTS idx_auth_identity_last_used_at ON auth_identity(last_used_at);

\echo '✓ Índices criados'

\echo '=== VERIFICAÇÃO FINAL: Estrutura da tabela ==='

-- 8. Verificar estrutura final
\d+ auth_identity

\echo '=== CONTAGEM FINAL ==='

SELECT 'Registros na tabela corrigida:' as info, COUNT(*) as count FROM auth_identity;
SELECT 'Registros no backup:' as info, COUNT(*) as count FROM auth_identity_backup_20260116;

\echo ''
\echo '============================================================'
\echo 'CORREÇÃO CONCLUÍDA COM SUCESSO!'
\echo '============================================================'
\echo ''
\echo 'PRÓXIMOS PASSOS:'
\echo '1. Reinicie o container Metabase: docker-compose restart dashboard'
\echo '2. Monitore os logs: docker-compose logs -f dashboard'
\echo '3. As migrações v58 devem completar automaticamente'
\echo ''
\echo 'BACKUP MANTIDO:'
\echo '- Tabela: auth_identity_backup_20260116'
\echo '- Para remover após confirmar: DROP TABLE auth_identity_backup_20260116;'
\echo '============================================================'
