-- ===================================================================
-- CORREÇÃO DEFINITIVA: Tabela auth_identity
-- Problema: user_id estava como UUID, deveria ser INTEGER
-- Solução: Recriar tabela com estrutura correta (sem erros)
-- ===================================================================

\set ON_ERROR_STOP on
\timing on

BEGIN;

\echo '════════════════════════════════════════════════════════════════'
\echo 'ETAPA 1: Criando backup de segurança'
\echo '════════════════════════════════════════════════════════════════'

DROP TABLE IF EXISTS auth_identity_backup_20260116 CASCADE;
CREATE TABLE auth_identity_backup_20260116 AS
SELECT * FROM auth_identity;

SELECT 'Backup criado:' as status, COUNT(*) as registros
FROM auth_identity_backup_20260116;

\echo '════════════════════════════════════════════════════════════════'
\echo 'ETAPA 2: Removendo constraints dependentes'
\echo '════════════════════════════════════════════════════════════════'

ALTER TABLE IF EXISTS auth_identity
    DROP CONSTRAINT IF EXISTS fk_auth_identity_core_user_id CASCADE;

ALTER TABLE IF EXISTS auth_identity
    DROP CONSTRAINT IF EXISTS auth_identity_user_id_provider_key CASCADE;

ALTER TABLE IF EXISTS auth_identity
    DROP CONSTRAINT IF EXISTS unique_user_provider CASCADE;

\echo '════════════════════════════════════════════════════════════════'
\echo 'ETAPA 3: Recriando tabela com estrutura correta'
\echo '════════════════════════════════════════════════════════════════'

DROP TABLE IF EXISTS auth_identity CASCADE;

CREATE TABLE auth_identity (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    provider VARCHAR(255) NOT NULL,
    provider_id VARCHAR(255),
    credentials JSONB,
    metadata JSONB,
    expires_at TIMESTAMP WITH TIME ZONE,
    last_used_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_user_provider UNIQUE (user_id, provider)
);

\echo 'Tabela auth_identity recriada com sucesso'

\echo '════════════════════════════════════════════════════════════════'
\echo 'ETAPA 4: Adicionando Foreign Key Constraint'
\echo '════════════════════════════════════════════════════════════════'

ALTER TABLE auth_identity
    ADD CONSTRAINT fk_auth_identity_core_user_id
    FOREIGN KEY (user_id)
    REFERENCES core_user(id)
    ON DELETE CASCADE;

\echo 'Foreign Key adicionada com sucesso'

\echo '════════════════════════════════════════════════════════════════'
\echo 'ETAPA 5: Criando índices de performance'
\echo '════════════════════════════════════════════════════════════════'

CREATE INDEX idx_auth_identity_user_id ON auth_identity(user_id);
CREATE INDEX idx_auth_identity_provider ON auth_identity(provider);
CREATE INDEX idx_auth_identity_last_used_at ON auth_identity(last_used_at);

\echo 'Índices criados com sucesso'

\echo '════════════════════════════════════════════════════════════════'
\echo 'ETAPA 6: Verificação final da estrutura'
\echo '════════════════════════════════════════════════════════════════'

SELECT
    column_name,
    data_type,
    is_nullable,
    column_default
FROM information_schema.columns
WHERE table_name = 'auth_identity'
ORDER BY ordinal_position;

\echo '════════════════════════════════════════════════════════════════'
\echo 'ETAPA 7: Verificando compatibilidade de tipos'
\echo '════════════════════════════════════════════════════════════════'

SELECT
    'core_user.id' as coluna,
    data_type as tipo
FROM information_schema.columns
WHERE table_name = 'core_user' AND column_name = 'id'
UNION ALL
SELECT
    'auth_identity.user_id' as coluna,
    data_type as tipo
FROM information_schema.columns
WHERE table_name = 'auth_identity' AND column_name = 'user_id';

\echo '════════════════════════════════════════════════════════════════'
\echo 'ETAPA 8: Resumo das constraints'
\echo '════════════════════════════════════════════════════════════════'

SELECT
    conname as constraint_name,
    contype as tipo,
    CASE contype
        WHEN 'p' THEN 'PRIMARY KEY'
        WHEN 'f' THEN 'FOREIGN KEY'
        WHEN 'u' THEN 'UNIQUE'
        WHEN 'c' THEN 'CHECK'
    END as descricao
FROM pg_constraint
WHERE conrelid = 'auth_identity'::regclass
ORDER BY contype;

COMMIT;

\echo ''
\echo '════════════════════════════════════════════════════════════════'
\echo '✓ CORREÇÃO CONCLUÍDA COM SUCESSO!'
\echo '════════════════════════════════════════════════════════════════'
\echo ''
\echo 'Próximos passos:'
\echo '1. Reiniciar container Metabase:'
\echo '   docker-compose restart dashboard'
\echo ''
\echo '2. Monitorar logs de migração:'
\echo '   docker-compose logs -f dashboard | grep -i migration'
\echo ''
\echo '3. As 38 migrações pendentes devem completar automaticamente'
\echo ''
\echo 'Backup mantido em: auth_identity_backup_20260116'
\echo '════════════════════════════════════════════════════════════════'
